using System.Collections.Generic;
using LegendsOfWarAndMagic.ProceduralGeneration.Core;
using LegendsOfWarAndMagic.ProceduralGeneration.WorldGeneration.Masks;
using UnityEngine;

namespace LegendsOfWarAndMagic.DebugTools.Snapshots
{
    public static class TerrainDataSerializer
    {
        public static object CaptureTerrainData(
            IProceduralTerrainSampler sampler,
            WorldGenerationMaskSet masks,
            Bounds area,
            int resolution)
        {
            var safeResolution = Mathf.Clamp(resolution, 5, 129);
            var heights = new List<List<float>>(safeResolution);
            var slopes = new List<List<float>>(safeResolution);
            var roadMask = new List<List<float>>(safeResolution);
            var stepX = safeResolution <= 1 ? 0f : area.size.x / (safeResolution - 1);
            var stepZ = safeResolution <= 1 ? 0f : area.size.z / (safeResolution - 1);

            for (var z = 0; z < safeResolution; z++)
            {
                var heightRow = new List<float>(safeResolution);
                var slopeRow = new List<float>(safeResolution);
                var roadRow = new List<float>(safeResolution);
                var worldZ = area.min.z + stepZ * z;
                for (var x = 0; x < safeResolution; x++)
                {
                    var worldX = area.min.x + stepX * x;
                    var height = sampler != null ? sampler.SampleHeightMeters(worldX, worldZ) : 0f;
                    var normal = sampler != null ? sampler.SampleNormal(worldX, worldZ) : Vector3.up;
                    heightRow.Add(height);
                    slopeRow.Add(Vector3.Angle(normal, Vector3.up));
                    roadRow.Add(masks != null ? masks.Evaluate(new Vector2(worldX, worldZ), GenerationZoneKind.Road) : 0f);
                }

                heights.Add(heightRow);
                slopes.Add(slopeRow);
                roadMask.Add(roadRow);
            }

            return new
            {
                area,
                resolution = safeResolution,
                coordinateSystem = "Unity world coordinates, X/Z horizontal, Y height in meters",
                heightmap = heights,
                slopeMapDegrees = slopes,
                roadMask,
                biomeMap = "not generated by the runtime location terrain pipeline",
                moistureMap = "not generated by the runtime location terrain pipeline",
                temperatureMap = "not generated by the runtime location terrain pipeline"
            };
        }

        public static Bounds ResolveSnapshotArea(Camera camera, Transform player, IReadOnlyList<Terrain> terrains, float radius = 420f)
        {
            var center = player != null ? player.position : camera != null ? camera.transform.position : Vector3.zero;
            if (camera != null)
            {
                center += Vector3.ProjectOnPlane(camera.transform.forward, Vector3.up).normalized * (radius * 0.35f);
            }

            var bounds = new Bounds(center, new Vector3(radius * 2f, 0f, radius * 2f));
            if (terrains == null || terrains.Count == 0)
            {
                return bounds;
            }

            var initialized = false;
            for (var i = 0; i < terrains.Count; i++)
            {
                var terrain = terrains[i];
                if (terrain == null || terrain.terrainData == null)
                {
                    continue;
                }

                var terrainBounds = new Bounds(
                    terrain.transform.position + terrain.terrainData.size * 0.5f,
                    terrain.terrainData.size);
                if (!initialized)
                {
                    bounds = terrainBounds;
                    initialized = true;
                }
                else
                {
                    bounds.Encapsulate(terrainBounds);
                }
            }

            return bounds;
        }
    }
}
